[package]
name = "onchain-registry"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "5.0.0-alpha.1", features = ["unit-testing", "legacy"] }
borsh = "1.0.0"

[dev-dependencies]
